export const SearchBarQueryHome = {
  products: [
    {
      id: 26,
      title: "Plant Hanger For Home TEST data",
      description:
        "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
      price: 41,
      discountPercentage: 17.86,
      rating: 4.08,
      stock: 131,
      brand: "Boho Decor",
      category: "home-decoration",
      thumbnail: "https://cdn.dummyjson.com/product-images/26/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/26/1.jpg",
        "https://cdn.dummyjson.com/product-images/26/2.jpg",
        "https://cdn.dummyjson.com/product-images/26/3.jpg",
        "https://cdn.dummyjson.com/product-images/26/4.jpg",
        "https://cdn.dummyjson.com/product-images/26/5.jpg",
        "https://cdn.dummyjson.com/product-images/26/thumbnail.jpg",
      ],
    },
    {
      id: 29,
      title: "Handcraft Chinese style",
      description:
        "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
      price: 60,
      discountPercentage: 15.34,
      rating: 4.44,
      stock: 7,
      brand: "luxury palace",
      category: "home-decoration",
      thumbnail: "https://cdn.dummyjson.com/product-images/29/thumbnail.webp",
      images: [
        "https://cdn.dummyjson.com/product-images/29/1.jpg",
        "https://cdn.dummyjson.com/product-images/29/2.jpg",
        "https://cdn.dummyjson.com/product-images/29/3.webp",
        "https://cdn.dummyjson.com/product-images/29/4.webp",
        "https://cdn.dummyjson.com/product-images/29/thumbnail.webp",
      ],
    },
    {
      id: 97,
      title: "Metal Ceramic Flower",
      description:
        "Metal Ceramic Flower Chandelier Home Lighting American Vintage Hanging Lighting Pendant Lamp",
      price: 35,
      discountPercentage: 10.94,
      rating: 4.93,
      stock: 146,
      brand: "Ifei Home",
      category: "lighting",
      thumbnail: "https://cdn.dummyjson.com/product-images/97/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/97/1.jpg",
        "https://cdn.dummyjson.com/product-images/97/2.jpg",
        "https://cdn.dummyjson.com/product-images/97/3.jpg",
        "https://cdn.dummyjson.com/product-images/97/4.webp",
        "https://cdn.dummyjson.com/product-images/97/thumbnail.jpg",
      ],
    },
  ],
  total: 3,
  skip: 0,
  limit: 3,
};

export const SearchBarQueryAll = {
  products: [
    {
      id: 4,
      title: "OPPOF19",
      description: "OPPO F19 is officially announced on April 2021.",
      price: 280,
      discountPercentage: 17.91,
      rating: 4.3,
      stock: 123,
      brand: "OPPO",
      category: "smartphones",
      thumbnail: "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/4/1.jpg",
        "https://cdn.dummyjson.com/product-images/4/2.jpg",
        "https://cdn.dummyjson.com/product-images/4/3.jpg",
        "https://cdn.dummyjson.com/product-images/4/4.jpg",
        "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
      ],
    },
    {
      id: 5,
      title: "Huawei P30",
      description:
        "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
      price: 499,
      discountPercentage: 10.58,
      rating: 4.09,
      stock: 32,
      brand: "Huawei",
      category: "smartphones",
      thumbnail: "https://cdn.dummyjson.com/product-images/5/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/5/1.jpg",
        "https://cdn.dummyjson.com/product-images/5/2.jpg",
        "https://cdn.dummyjson.com/product-images/5/3.jpg",
      ],
    },
    {
      id: 8,
      title: "Microsoft Surface Laptop 4",
      description:
        "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
      price: 1499,
      discountPercentage: 10.23,
      rating: 4.43,
      stock: 68,
      brand: "Microsoft Surface",
      category: "laptops",
      thumbnail: "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/8/1.jpg",
        "https://cdn.dummyjson.com/product-images/8/2.jpg",
        "https://cdn.dummyjson.com/product-images/8/3.jpg",
        "https://cdn.dummyjson.com/product-images/8/4.jpg",
        "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
      ],
    },
    {
      id: 18,
      title: "Oil Free Moisturizer 100ml",
      description:
        "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
      price: 40,
      discountPercentage: 13.1,
      rating: 4.56,
      stock: 88,
      brand: "Dermive",
      category: "skincare",
      thumbnail: "https://cdn.dummyjson.com/product-images/18/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/18/1.jpg",
        "https://cdn.dummyjson.com/product-images/18/2.jpg",
        "https://cdn.dummyjson.com/product-images/18/3.jpg",
        "https://cdn.dummyjson.com/product-images/18/4.jpg",
        "https://cdn.dummyjson.com/product-images/18/thumbnail.jpg",
      ],
    },
    {
      id: 26,
      title: "Plant Hanger For Home",
      description:
        "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
      price: 41,
      discountPercentage: 17.86,
      rating: 4.08,
      stock: 131,
      brand: "Boho Decor",
      category: "home-decoration",
      thumbnail: "https://cdn.dummyjson.com/product-images/26/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/26/1.jpg",
        "https://cdn.dummyjson.com/product-images/26/2.jpg",
        "https://cdn.dummyjson.com/product-images/26/3.jpg",
        "https://cdn.dummyjson.com/product-images/26/4.jpg",
        "https://cdn.dummyjson.com/product-images/26/5.jpg",
        "https://cdn.dummyjson.com/product-images/26/thumbnail.jpg",
      ],
    },
    {
      id: 28,
      title: "3D Embellishment Art Lamp",
      description:
        "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
      price: 20,
      discountPercentage: 16.49,
      rating: 4.82,
      stock: 54,
      brand: "LED Lights",
      category: "home-decoration",
      thumbnail: "https://cdn.dummyjson.com/product-images/28/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/28/1.jpg",
        "https://cdn.dummyjson.com/product-images/28/2.jpg",
        "https://cdn.dummyjson.com/product-images/28/3.png",
        "https://cdn.dummyjson.com/product-images/28/4.jpg",
        "https://cdn.dummyjson.com/product-images/28/thumbnail.jpg",
      ],
    },
    {
      id: 30,
      title: "Key Holder",
      description:
        "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
      price: 30,
      discountPercentage: 2.92,
      rating: 4.92,
      stock: 54,
      brand: "Golden",
      category: "home-decoration",
      thumbnail: "https://cdn.dummyjson.com/product-images/30/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/30/1.jpg",
        "https://cdn.dummyjson.com/product-images/30/2.jpg",
        "https://cdn.dummyjson.com/product-images/30/3.jpg",
        "https://cdn.dummyjson.com/product-images/30/thumbnail.jpg",
      ],
    },
    {
      id: 33,
      title: "3 Tier Corner Shelves",
      description:
        "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
      price: 700,
      discountPercentage: 17,
      rating: 4.31,
      stock: 106,
      brand: "Kitchen Shelf",
      category: "furniture",
      thumbnail: "https://cdn.dummyjson.com/product-images/33/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/33/1.jpg",
        "https://cdn.dummyjson.com/product-images/33/2.jpg",
        "https://cdn.dummyjson.com/product-images/33/3.jpg",
        "https://cdn.dummyjson.com/product-images/33/4.jpg",
        "https://cdn.dummyjson.com/product-images/33/thumbnail.jpg",
      ],
    },
    {
      id: 37,
      title: "ank Tops for Womens/Girls",
      description:
        "PACK OF 3 CAMISOLES ,VERY COMFORTABLE SOFT COTTON STUFF, COMFORTABLE IN ALL FOUR SEASONS",
      price: 50,
      discountPercentage: 12.05,
      rating: 4.52,
      stock: 107,
      brand: "Soft Cotton",
      category: "tops",
      thumbnail: "https://cdn.dummyjson.com/product-images/37/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/37/1.jpg",
        "https://cdn.dummyjson.com/product-images/37/2.jpg",
        "https://cdn.dummyjson.com/product-images/37/3.jpg",
        "https://cdn.dummyjson.com/product-images/37/4.jpg",
        "https://cdn.dummyjson.com/product-images/37/thumbnail.jpg",
      ],
    },
    {
      id: 39,
      title: "Women Sweaters Wool",
      description:
        "2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women' S Crop Top Sweater",
      price: 600,
      discountPercentage: 17.2,
      rating: 4.55,
      stock: 55,
      brand: "Top Sweater",
      category: "tops",
      thumbnail: "https://cdn.dummyjson.com/product-images/39/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/39/1.jpg",
        "https://cdn.dummyjson.com/product-images/39/2.jpg",
        "https://cdn.dummyjson.com/product-images/39/3.jpg",
        "https://cdn.dummyjson.com/product-images/39/4.jpg",
        "https://cdn.dummyjson.com/product-images/39/thumbnail.jpg",
      ],
    },
    {
      id: 44,
      title: "Ladies Multicolored Dress",
      description:
        "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
      price: 79,
      discountPercentage: 16.88,
      rating: 4.03,
      stock: 2,
      brand: "Ghazi Fabric",
      category: "womens-dresses",
      thumbnail: "https://cdn.dummyjson.com/product-images/44/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/44/1.jpg",
        "https://cdn.dummyjson.com/product-images/44/2.jpg",
        "https://cdn.dummyjson.com/product-images/44/3.jpg",
        "https://cdn.dummyjson.com/product-images/44/4.jpg",
        "https://cdn.dummyjson.com/product-images/44/thumbnail.jpg",
      ],
    },
    {
      id: 49,
      title: "Chappals & Shoe Ladies Metallic",
      description:
        "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
      price: 23,
      discountPercentage: 2.62,
      rating: 4.72,
      stock: 107,
      brand: "Maasai Sandals",
      category: "womens-shoes",
      thumbnail: "https://cdn.dummyjson.com/product-images/49/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/49/1.jpg",
        "https://cdn.dummyjson.com/product-images/49/2.jpg",
        "https://cdn.dummyjson.com/product-images/49/3.webp",
        "https://cdn.dummyjson.com/product-images/49/thumbnail.jpg",
      ],
    },
    {
      id: 67,
      title: "Fashion Magnetic Wrist Watch",
      description:
        "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
      price: 60,
      discountPercentage: 16.69,
      rating: 4.03,
      stock: 46,
      brand: "Eastern Watches",
      category: "womens-watches",
      thumbnail: "https://cdn.dummyjson.com/product-images/67/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/67/1.jpg",
        "https://cdn.dummyjson.com/product-images/67/2.jpg",
        "https://cdn.dummyjson.com/product-images/67/3.jpg",
        "https://cdn.dummyjson.com/product-images/67/4.jpg",
        "https://cdn.dummyjson.com/product-images/67/thumbnail.jpg",
      ],
    },
    {
      id: 89,
      title: "Qualcomm original Car Charger",
      description:
        "best Quality CHarger , Highly Recommended to all best Quality CHarger , Highly Recommended to all",
      price: 40,
      discountPercentage: 17.53,
      rating: 4.2,
      stock: 79,
      brand: "TC Reusable",
      category: "automotive",
      thumbnail: "https://cdn.dummyjson.com/product-images/89/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/89/1.jpg",
        "https://cdn.dummyjson.com/product-images/89/2.jpg",
        "https://cdn.dummyjson.com/product-images/89/3.jpg",
        "https://cdn.dummyjson.com/product-images/89/4.jpg",
        "https://cdn.dummyjson.com/product-images/89/thumbnail.jpg",
      ],
    },
    {
      id: 90,
      title: "Cycle Bike Glow",
      description:
        "Universal fitment and easy to install no special wires, can be easily installed and removed. Fits most standard tyre air stem valves of road, mountain bicycles, motocycles and cars.Bright led will turn on w",
      price: 35,
      discountPercentage: 11.08,
      rating: 4.1,
      stock: 63,
      brand: "Neon LED Light",
      category: "automotive",
      thumbnail: "https://cdn.dummyjson.com/product-images/90/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/90/1.jpg",
        "https://cdn.dummyjson.com/product-images/90/2.jpg",
        "https://cdn.dummyjson.com/product-images/90/3.jpg",
        "https://cdn.dummyjson.com/product-images/90/4.jpg",
        "https://cdn.dummyjson.com/product-images/90/thumbnail.jpg",
      ],
    },
  ],
  total: 15,
  skip: 0,
  limit: 15,
};

export const SearchBarQueryNoData = {
  products: [],
  total: 15,
  skip: 0,
  limit: 15,
};
